apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBTwxtZhOM0Tf46d85lD3FvwNsRc8NzT0ucYg2YWkoS1+almfpLWNbWZdcQiptAopgvXH5VRvpeY4zOBde5xQiD/B6AMXmfKp8iyGeILlLt7SxN/24hEGnw0rUuBqkO2POejRm0NrpZeEsCV+bR9MU4cD9qQPM9/c2N0JMj8WbG48E7yoCJpIjpl4vi5w0IEms4HXTcXh85pgz3xp2FIgok3q48ZjYFRhG/eNXBBW3P7AxnCVGi3JCxsgtB5HZU5/asrtDmV4TrtKVHjy1hzXJ8WATCtHOmhf1NWyAL/rOZPY9vYSA2RlPz3C48CSGMTrKxo01GqcK3p7LYVtgv7UPqYfmgDr0dH8KboqAfBn0LrNI3+7BP8mXpvWkNcQdZg4uhyERZufGrK8Zdept9x/b5ZLDzm8H+9ZwQtx2oE0CPrMFt+84F8S3rONEvCc4HpwVd3wVq95O8wxY+VCJ7PuTyeiFj5569iXXqAcVYtjHA6dSvZ2uwW1mySZL/ceNKgqEXOt/JYoQo3weIK/DeT9QBms3Oxx1xbdsjLHSHn8Rjq4dHx8eLm64JtXrwzYZmWa/WGDxSR8br9pJYTAmGjZTz9TwPNWRMS640IlGOoIXH3mhD/UHGt2E/HbomYchyyK6dCqTDzJjNGHmnP47epD7x1a6a3rq1ESB8xCXuDo5VuTMlDiz7skJ8YKo1XcrISanNiON3r14d5vovn4N3iQU8FV65Oo1WWWax
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

